### ISSUE TITLE
Quartz compatibility with Tomcat 10

### ISSUE THREAD

**Issue by chetna25884** [quartz-scheduler/quartz#794] opened 2022-04-22 15:14 UTC
Quartz latest version is dependent on javax namespace due to which it is not compatible with Tomcat 10. Is there any plan or estimate as to when will it be made compatible with Tomcat 10?

**Comment by sergey-morenets** [comment] 2022-06-19 08:53
Hi @chetna25884 

The easiest way here is to support two dependencies: for Jakarta EE 8(aka Java EE 8) and Jakarta EE 9. This is important migration process because Jakarta EE 10 will be released soon. And developers aren't able to make this transistion.

**Comment by alexsnaps** [comment] 2022-09-13 13:12
Based on what I'm seeing, I think it'd be best to provide a "jakarta version" of Quartz, just like how [ehcache did it](https://github.com/ehcache/ehcache3/issues/2946)? 

Am I missing anything: 
 - [ ] Jakarta Transaction API in core
 - [ ] JAX-RS in management

/cc @gsmet @jhouserizer

**Comment by ewsachse** [comment] 2022-12-13 20:21
This still an issue.   We need support for Jakarta EE 10, or Quartz will become unusable as we upgrade our applications to new runtimes that support Jakarta EE 10.

**Comment by gsmet** [comment] 2023-03-14 12:42
FWIW, in Quarkus, we are rewriting the Quartz classes at build time to make it compatible with EE 10.

**Comment by alexsnaps** [comment] 2023-03-14 13:30
It'd be nice to avoid having one, or worse multiple forks to start appearing.
If some guidance on the acceptance criteria for this to actually happen would be provided, some of us in the community would be glad to help... rather than having [stalebot decide](https://github.com/quartz-scheduler/quartz/pull/855) otherwise 😢

**Comment by vdotjansen** [comment] 2023-03-24 09:23
It seems that Spring boot 3 (Jakarta EE 9 (&10) compatible)  still contains quartz and supports Tomcat 10(.1)+ does anyone know what does not work exactly?

**Comment by jhouserizer** [comment] 2023-04-29 02:00
Quartz 2.5.0-rc1 is now on maven central.  This uses jakarta namespace.   Would be nice to have a few people try it out and give any feedback:


<dependency>
    <groupId>org.quartz-scheduler</groupId>
    <artifactId>quartz</artifactId>
    <version>2.5.0-rc1</version>
</dependency>

**Comment by calendarbudget** [comment] 2023-06-14 01:19
I'm using it now. It works for me in Tomcat 10, except I get the following error repeating every few minutes:

2023-06-13 21:16:02,388 ERROR JobRunShell               - Job JobSchedulingDataLoaderPlugin.JobSchedulingDataLoaderPlugin_jobInitializer_quartz_xml threw an unhandled Exception: 
java.lang.ClassCastException: class org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin cannot be cast to class org.quartz.jobs.FileScanListener (org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin and org.quartz.jobs.FileScanListener are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @28d3640c)
	at org.quartz.plugins.xml.FileScanJob.execute(FileScanJob.java:101)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2023-06-13 21:16:02,388 ERROR ErrorLogger               - Job (JobSchedulingDataLoaderPlugin.JobSchedulingDataLoaderPlugin_jobInitializer_quartz_xml threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.ClassCastException: class org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin cannot be cast to class org.quartz.jobs.FileScanListener (org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin and org.quartz.jobs.FileScanListener are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @28d3640c)]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.ClassCastException: class org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin cannot be cast to class org.quartz.jobs.FileScanListener (org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin and org.quartz.jobs.FileScanListener are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @28d3640c)
	at org.quartz.plugins.xml.FileScanJob.execute(FileScanJob.java:101)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more

**Comment by sgdesmet** [comment] 2023-07-14 07:35
Seems like `org.quartz.plugins.xml.FileScanJob` expects an `org.quartz.jobs.FileScanListener listener`: 

```
org.quartz.jobs.FileScanListener listener = (FileScanListener)schedCtxt.get(listenerName);
```

but `XMLSchedulingDataProcessorPlugin` implements `org.quartz.plugins.xml.FileScanListener`

**Comment by jonnybecker** [comment] 2023-07-17 13:00
Works for me on Tomcat 10.1. Thanks for your effort.

**Comment by olylak** [comment] 2023-07-23 15:54
> I'm using it now. It works for me in Tomcat 10, except I get the following error repeating every few minutes:
> 
> 2023-06-13 21:16:02,388 ERROR JobRunShell - Job JobSchedulingDataLoaderPlugin.JobSchedulingDataLoaderPlugin_jobInitializer_quartz_xml threw an unhandled Exception: java.lang.ClassCastException: class org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin cannot be cast to class org.quartz.jobs.FileScanListener (org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin and org.quartz.jobs.FileScanListener are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @28d3640c) at org.quartz.plugins.xml.FileScanJob.execute(FileScanJob.java:101) at org.quartz.core.JobRunShell.run(JobRunShell.java:202) at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) 2023-06-13 21:16:02,388 ERROR ErrorLogger - Job (JobSchedulingDataLoaderPlugin.JobSchedulingDataLoaderPlugin_jobInitializer_quartz_xml threw an exception. org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.ClassCastException: class org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin cannot be cast to class org.quartz.jobs.FileScanListener (org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin and org.quartz.jobs.FileScanListener are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @28d3640c)] at org.quartz.core.JobRunShell.run(JobRunShell.java:213) at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) Caused by: java.lang.ClassCastException: class org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin cannot be cast to class org.quartz.jobs.FileScanListener (org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin and org.quartz.jobs.FileScanListener are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @28d3640c) at org.quartz.plugins.xml.FileScanJob.execute(FileScanJob.java:101) at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ... 1 more

Hi @calendarbudget have you managed to fix it somehow?

Thanks

**Comment by calendarbudget** [comment] 2023-07-23 17:15
I had to revert back to Tomcat 8.5 for other reasons.
However, (not an ideal solution) I was able to stop the errors by turning off file scanning by setting the following in quartz.properties

org.quartz.plugin.jobInitializer.scanInterval = 0

**Comment by olylak** [comment] 2023-07-23 18:50
> I had to revert back to Tomcat 8.5 for other reasons. However, (not an ideal solution) I was able to stop the errors by turning off file scanning by setting the following in quartz.properties
> 
> org.quartz.plugin.jobInitializer.scanInterval = 0

Thanks a lot @calendarbudget!! Not ideal, but It works ;)

**Comment by kmr-mkondra** [comment] 2023-08-29 13:07
Hi Team,
We are looking forward to consume v2.5.0. Could you please let us know the release date?
Thanks...

**Comment by jscottjfs** [comment] 2023-12-29 21:39
We're seeing this with 2.5.0-rc1 and Tomcat 10.1.9 on server startup:

29-Dec-2023 15:56:57.096 SEVERE [main] org.apache.catalina.core.StandardContext.loadOnStartup Servlet [QuartzInitializer] in web application [/opuslib] threw load() exception
	java.lang.ClassCastException: class org.quartz.ee.servlet.QuartzInitializerServlet cannot be cast to class jakarta.servlet.Servlet (org.quartz.ee.servlet.QuartzInitializerServlet is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @5b970f7; jakarta.servlet.Servlet is in unnamed module of loader java.net.URLClassLoader @31221be2)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:865)
		at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:805)
		at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4633)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4926)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:713)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:975)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1949)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:776)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1656)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:898)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:846)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:871)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:241)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:910)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)

**Comment by Pruthula** [comment] 2024-01-20 08:43
Hi @jhouserizer 
I faced the same (above) issue in my project on upgrading to Tomcat 10 and Java 21 and I have a patch here for the fix. I was unable to create a Pull request for it since I dont have the permissions. Here is a patch, let me know if there is another way.
Thanks!
[pruthula-bugfixfilescanjob.patch](https://github.com/quartz-scheduler/quartz/files/13997345/pruthula-bugfixfilescanjob.patch)

**Comment by forrestasaur** [comment] 2024-03-04 20:34
Any plans to make a release candidate with the patch?

**Comment by kmr-mkondra** [comment] 2024-03-05 06:17
we are also looking for patch which supports tomcat 10

**Comment by jscottjfs** [comment] 2024-05-06 20:59
We also have problems with QuartzInitializerListener

06-May-2024 16:28:33.027 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [org.quartz.ee.servlet.QuartzInitializerListener]
	java.lang.NoClassDefFoundError: javax/servlet/ServletContextListener
		at java.base/java.lang.ClassLoader.defineClass1(Native Method)
		at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
		at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2487)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:865)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1401)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1245)
		at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:490)
		at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:472)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:142)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4381)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4892)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:713)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:975)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1949)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:776)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1656)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:898)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:846)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:871)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:241)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:910)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
	Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContextListener
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1437)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1245)

**Comment by jhouserizer** [comment] 2024-10-16 20:54
Looks like these issues (move to jakarta.servlet.*) were already addressed in previous commits/work , should be in upcoming release.

**Closed by jhouserizer** 2024-10-16 20:54 UTC
