### ISSUE TITLE
Cleanup pom setup and make build consistent

### ISSUE THREAD

**Issue by zemian** [quartz-scheduler/quartz#292] opened 2018-12-20 17:52 UTC
There are many things we can clean up the maven pom file and make build more smooth.

- [ ] Also the parent quartz/pom.xml is named "quartz-parent". It can use a more simple name as "quartz" instead.
- [ ] Remove unnecessary quartz/quartz module if possible
- [ ] Use properties in parent pom and used in other modules
- [ ] Declare pluginManagement and dependencyManagement with version, but use without version in modules.
- [ ] Remove unused plugins
- [ ] Use ${revision} for version label to reduce duplication.
- [ ] Get rid off maven javadoc WARNING messages during build
- [ ] Maven build warnings with javadoc plugin

**Comment by zemian** [comment] 2018-12-28 05:10
* Remove unnecessary quartz/quartz module if possible
* Use properties in parent pom and used in other modules
* Declare pluginManagement and dependencyManagement with version, but use without version in modules.
* Remove unused plugins
* Use ${revision} for version label to reduce duplication.

**Comment by zemian** [comment] 2019-04-01 15:49
It would be nice to remove unnecessary Terracotta specific repository and make Quartz more public users friendly. For example currently users are not able to build distribution package:

```
mvn package -DskipTests -Pdist
...
[ERROR] Plugin com.github.goldin:copy-maven-plugin:0.2.3.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.github.goldin:copy-maven-plugin:jar:0.2.3.8: Could not transfer artifact com.github.goldin:copy-maven-plugin:pom:0.2.3.8 from/to terracotta-releases (http://www.terracotta.org/download/reflector/releases): Access denied to: http://www.terracotta.org/download/reflector/releases/com/github/goldin/copy-maven-plugin/0.2.3.8/copy-maven-plugin-0.2.3.8.pom -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by mathieucarbou** [comment] 2022-10-03 11:51
> It would be nice to remove unnecessary Terracotta specific repository and make Quartz more public users friendly. For example currently users are not able to build distribution package:
> 
> ```
> mvn package -DskipTests -Pdist
> ...
> [ERROR] Plugin com.github.goldin:copy-maven-plugin:0.2.3.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.github.goldin:copy-maven-plugin:jar:0.2.3.8: Could not transfer artifact com.github.goldin:copy-maven-plugin:pom:0.2.3.8 from/to terracotta-releases (http://www.terracotta.org/download/reflector/releases): Access denied to: http://www.terracotta.org/download/reflector/releases/com/github/goldin/copy-maven-plugin/0.2.3.8/copy-maven-plugin-0.2.3.8.pom -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
> ```

@chrisdennis @akomakom : FYI I am re-opening because I am also having this same issue when running `./mvnw -s settings.xml clean install -Dmaven.test.skip.exec=true` with an empty settings.xml file on some older projects. I cannot find this plugin and one of its dependencies anywhere.

**Comment by jhouserizer** [comment] 2023-04-17 15:50
I'm closing this as I've just re-worked the build to use gradle.

There is still the problem that the tests must run without parallelization, but that's going to take further effort to resolve, as the problem is with the nature of several of the tests, not with the build system.

**Closed by jhouserizer** 2023-04-17 15:50 UTC
Labels: in:build
