### ISSUE TITLE
Quartz Job fired twice in cluster mode

### ISSUE THREAD

**Issue by upton** [quartz-scheduler/quartz#29] opened 2016-06-21 08:23 UTC
Quartz Job fired twice in cluster mode，see the detail bug : https://jira.terracotta.org/jira/browse/QTZ-453

**Comment by zemian** [comment] 2016-10-07 00:52
I don't see a test case in the QTZ-453. Need Review.

**Comment by Tanhe** [comment] 2017-02-16 16:39
I've had the same issue with the C# port. When acquiring triggers, shouldn't locking be used if in cluster mode? Currently the only check is for getAcquireTriggersWithinLock() || batchSize > 1....however setAcquireTrigersWithinLock(true) is not called if in clustered mode. There is a separate flag for "UseDBLocks" which isn't used.

I was going to submit a pull request on the C# port of this, and saw that the code is almost identical to the Java version.

I think this is the problem, but maybe one of the maintainers could weigh in.

I had a test installation setup where I could replicate the dual firing pretty easily if I let it run for a while. If I set the batchSize to a value > 1, which forced the use of locks in trigger acquisition, the dual firing went away.

**Comment by zhegexiaohuozi** [comment] 2017-03-13 09:08
I've had the same issue in version 2.2.1

**Comment by yangdailin** [comment] 2017-04-25 07:17
i had the same issue in version 2.2.1 in java

**Comment by prasad-babu** [comment] 2017-05-14 15:00
We have same problem (2.2.1 java). Issue is not reproducible with local instances(tried with test cases). However it is reproducible in customer instances. the only difference with customer instance is that the application is deployed in weblogic. Are there any chances to have problem with weblogic deployment with quartz? we use standard JNDI data source to get the connection

**Comment by jeffdotliatsapdotcom** [comment] 2017-07-05 21:20
I am here to report that we have the same issue too. We have two jobs that each was triggered twice. The trigger is simple interval trigger. The jobs are supposed to run daily at a fixed time. But sometimes, the jobs were run twice the same day.
Our server cluster has 16 nodes using quartz scheduler (quartz 2.2.1 java version). Each node is on VM on SAP cloud, and application is running inside Tomcat.
We can't reproduce the issue in house, but it did happen 3 times to our customer. 
I believe it'shard to reproduce because it's a racing condition problem, but it did happened, as well as the other reported.
It's a serious issue. Could the quartz team fix the problem?
Thanks.

**Comment by prasad-babu** [comment] 2017-07-18 04:00
My issue got resolved after adding property "org.quartz.jobStore.acquireTriggersWithinLoc" as true. But as per documentation, it is not necessary with latest build. However that is not the case

**Comment by jeffdotliatsapdotcom** [comment] 2017-07-28 22:16
I tried setting
org.quartz.jobStore.acquireTriggersWithinLock=true,
but I still saw the issue, still saw duplicate trigger executions

**Comment by pavelkokush** [comment] 2017-08-01 15:15
It might be because one of the node failed to do check-in in time? See [176](https://github.com/quartz-scheduler/quartz/issues/176)

**Comment by xuxueli** [comment] 2017-09-15 06:43
i had the same issue in version 2.3.0 in java.

**Comment by 1423302537** [comment] 2017-09-15 07:54
configure as 0 0/15 * * * ? will trigger twice，for example twice at 2017-09-14 15:00:01 ,2017-09-14 15:00:00,but 0 */15 * * * ? is ok

**Comment by 1423302537** [comment] 2017-09-15 07:54
version 2.3.0 in java.

**Comment by AdrianPT** [comment] 2018-02-16 16:44
Same problem here... v 2.6

**Comment by ihorpts** [comment] 2018-02-22 12:58
we went to production with version 2.2.3 and get this issue from time to time as well. We don't use @DisallowConcurrentExecution annotation in our jobs.

**Comment by yparkhi** [comment] 2018-03-13 08:23
experiencing this issue and reported a defect in our agile board.

**Comment by ihorpts** [comment] 2018-04-05 11:56
hi all
Somehow I couldn't create an account at http://ww1.terracotta.org/account/register to be able to add reproducer to the https://jira.terracotta.org/jira/browse/QTZ-453 ticket, so I'm posting it here.

1. As I wrote before - we have the same issue (seems to be) as described here: double fire of a quartz job. What we did is just migrate from 1.8.3 version up to 2.2.3. No configuration changes were done except of compilation error fixes.
2. It's bothering as a lot in PRODUCTION now. So, I've tried to do a reproducer (see attached maven project). I'm trying to debug it now and understand if I missing some additional configuration or it's some bug in quartz itself. 
3. Here is some additional info about the reproducer project, how to run it and another information:
3.1. It's a maven project, which produces an executable "fat" jar with all needed depndencies
3.2. After it's compiled it can be started as ``` java -jar quartz-dist-1.0-SNAPSHOT-jar-with-dependencies.jar```
3.3. Configuration for DS is placed in ```quartz.properties``` file
3.4. Very interesting thing is that it can be reproducible in deterministic way only when I run two instances of quartz app (cluster) one from Linux and another one from my VM with Windows. If I execute it in two different JVM but on the same host (be it Linux or Windows) it works fine.
3.5. I've tried to add ```@DisallowConcurrentExecution```. It actually just reduces the probability of double firing of the same job. But it's still possible to simulate it (1 ouf ot 10 executes, like stop and start two nodes)
3.6. Additional info:

       Linux: Ubuntu 16.04
       Java: jdk_1.8.0_152

       Windows 7: SP1
       Java: jdk_1.8.0_161

       Oracle DB: 12.1c
       Maven: 3.5.0

Hope it will help to investigate the issue or find out if it's the proper use-case for such simulation of the problem.

[quartzdist.zip](https://github.com/quartz-scheduler/quartz/files/1879875/quartzdist.zip)

**Comment by lvdelu** [comment] 2018-04-16 09:03
I had the same issue in version 2.2.1 in java

**Comment by chxiaowu** [comment] 2018-05-10 03:03
Any update？ I have the same issue， version ： 2.2.3 and I am using mongdob.
https://github.com/michaelklishin/quartz-mongodb
but my problem is the trigger times is same as thread count.

![default](https://user-images.githubusercontent.com/3086363/39850002-bc9e2fdc-5441-11e8-9dab-4a2c6ab71f6a.png)

**Comment by zemian** [comment] 2019-02-15 20:13
Hi, this is likely duplicate of this issue #107 Please try the solution propose and reopen if you still it's different issue.

**Closed by zemian** 2019-02-15 20:13 UTC
Labels: cannot reproduce, need review

**Comment by way2nikhil** [comment] 2019-08-16 16:40
Commenting on closed thread , but wanted to understand if this reproduces only when recoveryrequested= true or otherwise also.
@prasad-babu  @yangdailin  @jhouserizer @upton 
btw we are using oracle database seeing this issue when recoveryrequested= true and acquireTriggersWithinLock=true and vm time are in sync.

**Comment by ashrafsarhan** [comment] 2022-08-30 12:28
I had the same issue before but I discovered that I was calling `scheduler.scheduleJob(job, trigger); `  to update the job data while the job is running which is randomly triggered the job 5-6 times each run. I had to use the following to update the job data without updating the trigger `scheduler.addJob(job, true); `

**Comment by EduFrazao** [comment] 2024-07-01 18:58
> Commenting on closed thread , but wanted to understand if this reproduces only when recoveryrequested= true or otherwise also. @prasad-babu @yangdailin @jhouserizer @upton btw we are using oracle database seeing this issue when recoveryrequested= true and acquireTriggersWithinLock=true and vm time are in sync.

Hi @way2nikhil . Sorry to cite you on a closed thread, but i'm still having this problem with Quartz 2.2.3, with Oracle, recoveryrequested= true and acquireTriggersWithinLock=true. Do you have found any workaround this problem?
