### ISSUE TITLE
Bad misfire jobs breaks the trigger process

### ISSUE THREAD

**Issue by rhishirajnema** [quartz-scheduler/quartz#263] opened 2018-10-02 18:59 UTC
We have a bad misfired job and everytime scheduler it starts it throws this error - 
```
org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3940)
MisfireHandler: Error handling misfires: Couldn't store trigger
at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1223)
at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1037)
at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:986)
at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3187)
at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3935)
at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3956)
Caused by: java.io.InvalidClassException
```
This does not let other jobs to trigger and they keep accumulating, is there a way to perform exception handling for MisfireHandler?

**Comment by zemian** [comment] 2018-12-18 01:41
Looks like you have a bad DB table that prevent Quartz to store/update the trigger data. Your last line says "InvalidClassException", so perhaps you need to trace the root cause. Perhaps you misconfigured the trigger or datamap that associate with it.

**Comment by zemian** [comment] 2018-12-29 04:33
I agree that this is a good feature to have, but unfortunately currently it's not supported. You have to find your original class and use API to remove, or manually remove the data from DATA in order to resolve this.

**Comment by zemian** [comment] 2019-02-15 22:10
Closing outdated, unresolved issues. Please, reopen if still relevant.

**Closed by zemian** 2019-02-15 22:10 UTC
Labels: wont fix
