### ISSUE TITLE
Job loss suddenly

### ISSUE THREAD

**Issue by suYaoXing** [quartz-scheduler/quartz#247] opened 2018-07-16 10:11 UTC
I created a Job that runs at 9:00 every day on July 5th,and from July 5th to July 9th,it worked well,but on July 10th,it didn't run and I checked my database ,found that all the tables about quartz were empty,so I wonder why my job didn't run suddenly,and why my job data was lost.Thanks a lot.The following is my 
code snippet.

QuartzConfig.java:
public class QuartzConfig {
	@Autowired
	private SpringJobFactory factory;

	@Value("${quartz.jdbc.url}")
	private String url;

	@Value("${quartz.jdbc.username}")
	private String username;

	@Value("${quartz.jdbc.password}")
	private String password;

	@Value("${quartz.jdbc.database}")
	private String database;

	@Value("${quartz.jdbc.driver}")
	private String driver;

	@Bean(name="SchedulerFactory")
	public SchedulerFactoryBean schedulerFactoryBean() throws Exception {
		SchedulerFactoryBean factoryBean = new SchedulerFactoryBean();
		factoryBean.setAutoStartup(true);
		factoryBean.setStartupDelay(0);
		factoryBean.setJobFactory(factory);
		factoryBean.setQuartzProperties(p);
		factoryBean.setDataSource(datasource());
		return factoryBean;
	}

	public DataSource datasource() {
		DruidXADataSource dataSource = new DruidXADataSource();
		dataSource.setUrl(url);
		dataSource.setPassword(password);
		dataSource.setUsername(username);
		dataSource.setDefaultCatalog(database);
		dataSource.setDriverClassName(driver);
		return dataSource;
	}

	@Bean
	public QuartzInitializerListener executorListener() {
		return new QuartzInitializerListener();
	}

	@Bean(name="Scheduler")
	public Scheduler scheduler() throws Exception {
		return schedulerFactoryBean().getScheduler();
	}
}

the code of creating job:
CronScheduleBuilder cronScheduleBuilder =  CronScheduleBuilder.cronSchedule("0 0 9 * * ?");
JobDetail job = JobBuilder.newJob(DemoJob.class).withDescription("check and send mail at 9 everyday").
withIdentity("demojob", "demojobGroup").storeDurably(true).build();
Trigger trigger = TriggerBuilder.newTrigger().withSchedule(cronScheduleBuilder).startNow().withIdentity("demojobTrigger", "demojobTriggerGroup").build();

**Comment by tnote** [comment] 2018-07-24 08:58
I met the same problem. 
2018-07-24 15:11:48.129 ERROR 7316 --- [QuartzScheduler_SchedulerFactory-NON_CLUSTERED_MisfireHandler] org.quartz.impl.jdbcjobstore.JobStoreTX  : MisfireHandler: Error handling misfires: Database error recovering from misfires.

org.quartz.JobPersistenceException: Database error recovering from misfires.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3259) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3997) [quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4018) [quartz-2.3.0.jar:na]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'bailun_datacenter.qrtz_triggers' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_161]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_161]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76) ~[c3p0-0.9.1.2.jar:0.9.1.2]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3238) ~[quartz-2.3.0.jar:na]
	... 2 common frames omitted

**Comment by suYaoXing** [comment] 2018-07-24 09:42
it looks like a problem thart occured in Database.

**Comment by tnote** [comment] 2018-07-26 01:48
Oh, my colleague truancated table qrtz_triggers when I didn't pay attention to it.........

**Comment by zemian** [comment] 2018-12-31 04:32
This does not look like Quartz problem. Quartz only remove data from DB on it's own if the job is not setup repeatedly and actually end after certain date. If this is user error, then we can close the issue.

**Comment by zemian** [comment] 2019-02-15 22:14
Closing outdated, unresolved issues. Please, reopen if still relevant. 

See https://github.com/quartz-scheduler/quartz/wiki/How-To-Submit-New-Issue

**Closed by zemian** 2019-02-15 22:14 UTC
Labels: invalid
